In [1]:
import pandas as pd

In [2]:
# Import DataFrames from CSV files
Personal_Info = pd.read_csv('Personal_Info.csv')
Skill_Exchange = pd.read_csv('Skill_Exchange.csv')
Track_Record = pd.read_csv('Track_Record.csv')
Feedback = pd.read_csv('Feedback.csv')


# Concatenate DataFrames horizontally
combined_df = pd.concat([Personal_Info, Skill_Exchange, Track_Record, Feedback], axis=1)

combined_df.head()

,First_Name,EMail,Age,Gender,Coordinate,Country,City,Languages_Preferred,Last_Seen,Response_Time,...,Self_Defense_and_Personal_Safety_dem,Healthcare_and_Nutrition_dem,Count_Skills_Rec,Count_Skills_Off,Rec_to_Off_Ratio,Usability,Speed_Performance,Feature_Satisfaction,Security_Satisfaction,Customer_Support
0,Wanda,wanda.opizzi@aol.com,46,Male,"(52.48592054317992, 13.597034412185927)",Germany,Berlin,"['English', 'Italian', 'Ukrainian', 'Turkish '...",Over a Month Ago,Within a week,...,Expert,Advanced,169,184,0.92,Neutral or Average,Very Dissatisfied,Dissatisfied,Dissatisfied,Dissatisfied
1,Meinrad,meinrad.kiedrowicz@zoho.com,26,Other,"(52.59690466818614, 13.725347983308117)",Germany,Berlin,"['German', 'Punjabi', 'Spanish', 'Arabic']",Within a Week,Within 24 hours,...,Advanced,Novice,40,42,0.95,Very Satisfied,Neutral or Average,Dissatisfied,Satisfied,Very Dissatisfied
2,Derkay,derkay.kurach@outlook.com,41,Male,"(52.56108833495195, 13.18563761680123)",Germany,Berlin,"['Hindi', 'Japanese']",Within a Week,Within 24 hours,...,Novice,Advanced,118,100,1.18,Very Dissatisfied,Satisfied,Very Dissatisfied,Very Satisfied,Dissatisfied
3,Uzsoy,uzsoy.akdeniz@freenet.de,54,Male,"(52.443532336864735, 13.419956868448828)",Germany,Berlin,['Romanian'],Within a Week,Within 24 hours,...,Novice,Novice,83,68,1.22,Neutral or Average,Neutral or Average,Neutral or Average,Very Satisfied,Neutral or Average
4,Alpsü,alpsü.demirel@icloud.com,19,Female,"(52.36608543756369, 13.10990718388389)",Germany,Berlin,"['Arabic', 'Portuguese', 'Mandarin Chinese', '...",Within a Week,Within a month,...,Novice,Advanced,142,152,0.93,Dissatisfied,Very Dissatisfied,Very Dissatisfied,Dissatisfied,Very Satisfied

In [3]:
combined_df.to_csv('Skillswap_Data_Raw.csv', index=False)