In [5]:
import pandas as pd

In [6]:
# Import DataFrames from CSV files
Skill_Exchange_Offered_uncleaned = pd.read_csv('Skill_Exchange_Offered.csv')
Skill_Exchange_Offered = Skill_Exchange_Offered_uncleaned.drop(columns=["Expert_skill", "Matched_skills_samples"])

# -- To be cleared --
# Skill_Exchange_Demanded = pd.read_csv('Skill_Exchange_Demanded.csv')


# -- To be cleared --
# Concatenate DataFrames horizontally
# Skill_Exchange = pd.concat([Skill_Exchange_Offered, Skill_Exchange_Demanded], axis=1)

Skill_Exchange = Skill_Exchange_Offered

Skill_Exchange.head()

,Programming_and_Software_Development_off,Project_Management_off,Accounting_and_Finance_off,Marketing_and_Advertising_off,Sales_and_Customer_Service_off,Human_Resources_and_Leadership_off,Graphic_Design_and_Illustration_off,Photography_and_Photo_Editing_off,Music_instruments_Composition_and_Production_off,Writing_and_Editing_off,...,Mathematics_and_Sciences_off,History_and_Social_Sciences_off,Literature_and_Philosophy_off,Research_Methods_and_Academic_Writing_off,Academic_Reading_and_Critique_off,Time_Management_and_Organization_off,Stress_Management_and_Mindfulness_off,Financial_Planning_and_Budgeting_off,Self_Defense_and_Personal_Safety_off,Healthcare_and_Nutrition_off
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Novice,Novice,Advanced,Novice,Beginner,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Novice,Novice,Beginner,Novice,Intermediate,Expert,Beginner,Beginner,Novice,Novice
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Beginner,Novice,Expert,Beginner,Novice

In [7]:
Skill_Exchange.to_csv('Skill_Exchange.csv', index=False)