In [2]:
import pandas as pd
import random

In [3]:
# Create lists containing the number of skills offered and taken
Count_Skills_Off = []
Count_Skills_Rec = []
Rec_to_Off_Ratio = []

In [4]:
# Ensure a good ratio between skills offered and received
# Calculate the maximum deviation allowed for a given ratio.
# Calculate the maximum allowable deviation based on received skills

def calculate_max_deviation(count_received, max_deviation_percent):
    max_deviation = count_received * max_deviation_percent / 100.0
    return max_deviation

# Define parameters
# try to keep the ratio at 1:1 skill offered / received with a maximum 
# allowable deviation percentage of 20% 

max_deviation_percent = 20
max_count = 300  
num_iterations = 750

# Generate random skills received and calculate skills offered within a deviation range
# Generate random count of skills received
# Calculate the maximum deviation allowed for skills offered based on received skills
# Generate count of skills offered within the deviation range
# Append values to the lists
# Calculate and append the ratio

for _ in range(num_iterations):
    count_received = random.randint(1, max_count)
    
    max_deviation = calculate_max_deviation(count_received, max_deviation_percent)
    
    count_offered = random.randint(max(1, count_received - round(max_deviation)), min(max_count, count_received + round(max_deviation)))
    
    Count_Skills_Rec.append(count_received)
    Count_Skills_Off.append(count_offered)
    
    ratio = round(count_received / count_offered, 2)
    Rec_to_Off_Ratio.append(ratio)

In [5]:
# Create a data frame
table = {
    'Count_Skills_Rec': Count_Skills_Rec,
    'Count_Skills_Off': Count_Skills_Off,
    'Rec_to_Off_Ratio': Rec_to_Off_Ratio
}

Track_Record = pd.DataFrame(table)
Track_Record.head(100)

    Count_Skills_Rec  Count_Skills_Off  Rec_to_Off_Ratio
0                 39                40              0.97
1                 18                20              0.90
2                291               259              1.12
3                211               172              1.23
4                 23                25              0.92
..               ...               ...               ...
95               282               253              1.11
96                94                97              0.97
97               136               147              0.93
98               175               191              0.92
99                68                69              0.99

[100 rows x 3 columns]

In [5]:
Track_Record.to_csv('Track_Record.csv', index=False)

In [10]:
# Create Overview over dtypes
column_info = []

for column, dtype in Track_Record.dtypes.items():
    column_info.append((column, str(dtype)))
    
df_column_info = pd.DataFrame(column_info, columns=['User Data', 'Data Type'])
df_column_info['Factor'] = 'Track_Record'
factor_column = df_column_info.pop('Factor')

# Insert the "Factor" column as the first column
df_column_info.insert(0, 'Factor', factor_column)
df_column_info.head()

         Factor         User Data Data Type
0  Track_Record  Count_Skills_Rec     int64
1  Track_Record  Count_Skills_Off     int64
2  Track_Record  Rec_to_Off_Ratio   float64

In [11]:
df_column_info.to_csv('dtype_Track_Record.csv', index=False)