In [19]:
import pandas as pd

In [20]:
df = pd.read_csv(r'C:\Users\Johannes\Documents\ws24-skillswap\DS\01_Notebooks\01_Synthetic_Data_Set\Skillswap_Data_Raw.csv')

df.head()

,First_Name,EMail,Age,Gender,Location_Preferences,Latitude,Longitude,Country,City,Languages_Preferred,...,Sports,Food,Technology,Photo,Video,Usability,Speed_Performance,Feature_Satisfaction,Security_Satisfaction,Customer_Support
0,Kandef,kandef.fechner@freenet.de,28,Prefer not to say,Local Only,52.548727,13.534825,Germany,Berlin,['Bengali'],...,10.0,NaN,NaN,NaN,NaN,Satisfied,Satisfied,Satisfied,Very Satisfied,Very Satisfied
1,Sonia,sonia.conte@hotmail.com,25,Prefer not to say,Local or Remote,52.380775,13.596353,Germany,Berlin,"['Polish', 'Turkish', 'Japanese']",...,NaN,NaN,NaN,NaN,NaN,Neutral or Average,Dissatisfied,Dissatisfied,Dissatisfied,Very Dissatisfied
2,Marek,marek.gough@gmail.com,24,Male,Local or Remote,52.420733,13.722983,Germany,Berlin,['Punjabi'],...,NaN,NaN,NaN,NaN,NaN,Very Satisfied,Neutral or Average,Dissatisfied,Satisfied,Satisfied
3,Seve,seve.manjón@freenet.de,29,Female,Local or Remote,52.497656,13.244198,Germany,Berlin,"['Japanese', 'French']",...,NaN,NaN,NaN,NaN,NaN,Neutral or Average,Dissatisfied,Very Satisfied,Very Satisfied,Satisfied
4,Bernard,bernard.hançer@unitybox.de,28,Male,Local or Remote,52.365487,13.121122,Germany,Berlin,['Romanian'],...,NaN,NaN,NaN,NaN,NaN,Dissatisfied,Neutral or Average,Satisfied,Very Satisfied,Very Satisfied

In [21]:
# Label Data with Activity Status

df['Activity_Status'] = ""

average_sum_skills = df['Sum_Skills_Off'].mean()
df['Sum_Skills_Off_ab_avg'] = df['Sum_Skills_Off'].apply(lambda x: 1 if x > average_sum_skills else 0)

for index, row in df.iterrows():
    if row['Last_Seen'] in ["Recently", "Today", "Yesterday", "Within a Week"] and \
            row['Response_Time'] in ["Within 24 hours", "Within a week"] and \
            row['Sum_Skills_Off_ab_avg'] == 1:
        df.at[index, 'Activity_Status'] = "Swapper"
    elif row['Last_Seen'] in ["Recently", "Today", "Yesterday", "Within a Week"] and \
            row['Response_Time'] in ["Within 24 hours", "Within a week"] and \
            row['Sum_Skills_Off_ab_avg'] == 0:
        df.at[index, 'Activity_Status'] = "Active User"
    elif row['Last_Seen'] == "Within a Month" or row['Response_Time'] == "Within a month":
        df.at[index, 'Activity_Status'] = "Occasional User"
    elif row['Last_Seen'] == "Over a Month Ago" or row['Response_Time'] == "More than a month":
        df.at[index, 'Activity_Status'] = "Inactive"
    else:
        df.at[index, 'Activity_Status'] = pd.NA 

df.head()

,First_Name,EMail,Age,Gender,Location_Preferences,Latitude,Longitude,Country,City,Languages_Preferred,...,Technology,Photo,Video,Usability,Speed_Performance,Feature_Satisfaction,Security_Satisfaction,Customer_Support,Activity_Status,Sum_Skills_Off_ab_avg
0,Kandef,kandef.fechner@freenet.de,28,Prefer not to say,Local Only,52.548727,13.534825,Germany,Berlin,['Bengali'],...,NaN,NaN,NaN,Satisfied,Satisfied,Satisfied,Very Satisfied,Very Satisfied,Swapper,1
1,Sonia,sonia.conte@hotmail.com,25,Prefer not to say,Local or Remote,52.380775,13.596353,Germany,Berlin,"['Polish', 'Turkish', 'Japanese']",...,NaN,NaN,NaN,Neutral or Average,Dissatisfied,Dissatisfied,Dissatisfied,Very Dissatisfied,Inactive,0
2,Marek,marek.gough@gmail.com,24,Male,Local or Remote,52.420733,13.722983,Germany,Berlin,['Punjabi'],...,NaN,NaN,NaN,Very Satisfied,Neutral or Average,Dissatisfied,Satisfied,Satisfied,Swapper,1
3,Seve,seve.manjón@freenet.de,29,Female,Local or Remote,52.497656,13.244198,Germany,Berlin,"['Japanese', 'French']",...,NaN,NaN,NaN,Neutral or Average,Dissatisfied,Very Satisfied,Very Satisfied,Satisfied,Occasional User,1
4,Bernard,bernard.hançer@unitybox.de,28,Male,Local or Remote,52.365487,13.121122,Germany,Berlin,['Romanian'],...,NaN,NaN,NaN,Dissatisfied,Neutral or Average,Satisfied,Very Satisfied,Very Satisfied,Inactive,0

In [22]:
# Check NA Values
empty_values = df['Activity_Status'].isna().sum()

print("Number of empty values in the 'Activity_Status' column:", empty_values)

Number of empty values in the 'Activity_Status' column: 0

In [23]:
# Count unique values
activity_status_counts = df['Activity_Status'].value_counts()

print("Count of unique values in the 'Activity_Status' column:")
print(activity_status_counts)

Count of unique values in the 'Activity_Status' column:
Activity_Status
Occasional User    237
Swapper            229
Active User        225
Inactive           109
Name: count, dtype: int64

In [24]:
df.to_csv('Skillswap_Data_Activity_Status.csv', index=False)