In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a Dataframe, to count how many times a skill was offered
lists_dict = {
    "Count_Farming_off": [],
"Count_Fishery_off": [],
"Count_Gardening_off": [],
"Count_Pet_grooming_off": [],
"Count_Pet_training_off": [],
"Count_Drawing_off": [],
"Count_Painting_off": [],
"Count_Sculpture_off": [],
"Count_Print_making_off": [],
"Count_Poetry_off": [],
"Count_Make_up_off": [],
"Count_Facials_off": [],
"Count_Pedicure_and_Manicure_off": [],
"Count_Hair_care_off": [],
"Count_Ballet_off": [],
"Count_Tap_dance_off": [],
"Count_Jazz_dance_off": [],
"Count_Salsa_off": [],
"Count_Ballroom_dance_off": [],
"Count_Piano_off": [],
"Count_Guitar_off": [],
"Count_Drumming_off": [],
"Count_Trumpet_off": [],
"Count_Composing_off": [],
"Count_Script_writing_off": [],
"Count_Play_writing_off": [],
"Count_Poetry_writing_off": [],
"Count_Caligraphy_off": [],
"Count_Blogging_off": [],
"Count_Journalism_off": [],
"Count_German_off": [],
"Count_Spanish_off": [],
"Count_Arabic_off": [],
"Count_French_off": [],
"Count_English_off": [],
"Count_Nutrition_off": [],
"Count_Fitness_and_Excercise_off": [],
"Count_Wellness_off": [],
"Count_Tennis_off": [],
"Count_Football_off": [],
"Count_Basketball_off": [],
"Count_Yoga_off": [],
"Count_Baseball_off": [],
"Count_Gymnastic_off": [],
"Count_Cooking_off": [],
"Count_Baking_off": [],
"Count_Grilling_off": [],
"Count_Meal_planning_off": [],
"Count_Sautéing_off": [],
"Count_Programming_off": [],
"Count_Graphic_design_off": [],
"Count_Data_Analysis_off": [],
"Count_Photoshop_off": [],
"Count_Social_Media_off": [],
"Count_Camera_handling_off": [],
"Count_Photo_editing_off": [],
"Count_Lighting_off": [],
"Count_Landscape_photography_off": [],
"Count_Portrait_photography_off": [],
"Count_Image_processing_off": [],
"Count_Video_editing_off": [],
"Count_Film_making_off": [],
"Count_Animation_off": [],
"Count_Motion_graphics_off": [],
"Count_Visual_effects_off": []
}


Count_df = pd.DataFrame(lists_dict)

Count_df

Empty DataFrame
Columns: [Count_Farming_off, Count_Fishery_off, Count_Gardening_off, Count_Pet_grooming_off, Count_Pet_training_off, Count_Drawing_off, Count_Painting_off, Count_Sculpture_off, Count_Print_making_off, Count_Poetry_off, Count_Make_up_off, Count_Facials_off, Count_Pedicure_and_Manicure_off, Count_Hair_care_off, Count_Ballet_off, Count_Tap_dance_off, Count_Jazz_dance_off, Count_Salsa_off, Count_Ballroom_dance_off, Count_Piano_off, Count_Guitar_off, Count_Drumming_off, Count_Trumpet_off, Count_Composing_off, Count_Script_writing_off, Count_Play_writing_off, Count_Poetry_writing_off, Count_Caligraphy_off, Count_Blogging_off, Count_Journalism_off, Count_German_off, Count_Spanish_off, Count_Arabic_off, Count_French_off, Count_English_off, Count_Nutrition_off, Count_Fitness_and_Excercise_off, Count_Wellness_off, Count_Tennis_off, Count_Football_off, Count_Basketball_off, Count_Yoga_off, Count_Baseball_off, Count_Gymnastic_off, Count_Cooking_off, Count_Baking_off, Count_Grilling_off, Count_Meal_planning_off, Count_Sautéing_off, Count_Programming_off, Count_Graphic_design_off, Count_Data_Analysis_off, Count_Photoshop_off, Count_Social_Media_off, Count_Camera_handling_off, Count_Photo_editing_off, Count_Lighting_off, Count_Landscape_photography_off, Count_Portrait_photography_off, Count_Image_processing_off, Count_Video_editing_off, Count_Film_making_off, Count_Animation_off, Count_Motion_graphics_off, Count_Visual_effects_off]
Index: []

[0 rows x 65 columns]

In [3]:
Skill_Exchange_Offered = pd.read_csv('Skill_Exchange_Offered.csv')
Skill_Exchange_Offered

,Farming_off,Fishery_off,Gardening_off,Pet grooming_off,Pet training_off,Drawing_off,Painting_off,Sculpture_off,Print making_off,Poetry_off,...,Portrait photography_off,Image processing_off,Video editing_off,Film making_off,Animation_off,Motion graphics_off,Visual effects_off,Expert_skill,Matched_skills_samples,Skill Domains
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tennis_off,"['German_off', 'Spanish_off', 'Arabic_off', 'F...","['Language', 'Sports']"
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Novice,Intermediate,Intermediate,Beginner,Novice,Graphic design_off,"['Video editing_off', 'Film making_off', 'Anim...","['Video', 'Technology', 'Writing']"
2,Expert,Novice,Intermediate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farming_off,"['Piano_off', 'Guitar_off', 'Drumming_off', 'T...","['Music', 'Agriculture', 'Language']"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Football_off,"['Ballet_off', 'Tap dance_off', 'Jazz dance_of...","['Dance', 'Sports']"
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Novice,Novice,Advanced,Novice,Intermediate,Pedicure & Manicure_off,"['Make-up_off', 'Facials_off', 'Hair care_off'...","['Beauty', 'Video']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Analysis_off,"['Programming_off', 'Graphic design_off', 'Pho...",['Technology']
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Drumming_off,"['Piano_off', 'Guitar_off', 'Trumpet_off', 'Co...","['Music', 'Writing']"
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blogging_off,"['Cooking_off', 'Baking_off', 'Grilling_off', ...","['Food', 'Writing']"
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Piano_off,"['Cooking_off', 'Baking_off', 'Grilling_off', ...","['Food', 'Music']"
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yoga_off,"['Tennis_off', 'Football_off', 'Basketball_off...",['Sports']

In [4]:
# Take Expert_Skill dataframe to see where a person can teach (assuming that you can at least teach a skill where you are an expert)
expert_skill = pd.DataFrame(Skill_Exchange_Offered, columns=["Expert_skill"])
expert_skill['Expert_skill'] = expert_skill['Expert_skill'].apply(lambda x: 'Count_' + str(x))
expert_skill

                      Expert_skill
0                 Count_Tennis_off
1         Count_Graphic design_off
2                Count_Farming_off
3               Count_Football_off
4    Count_Pedicure & Manicure_off
..                             ...
795        Count_Data Analysis_off
796             Count_Drumming_off
797             Count_Blogging_off
798                Count_Piano_off
799                 Count_Yoga_off

[800 rows x 1 columns]

In [5]:
concatenated_df = pd.concat([Count_df, expert_skill], axis=1)
concatenated_df

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,...,Count_Lighting_off,Count_Landscape_photography_off,Count_Portrait_photography_off,Count_Image_processing_off,Count_Video_editing_off,Count_Film_making_off,Count_Animation_off,Count_Motion_graphics_off,Count_Visual_effects_off,Expert_skill
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Tennis_off
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Graphic design_off
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Farming_off
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Football_off
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Pedicure & Manicure_off
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Data Analysis_off
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Drumming_off
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Blogging_off
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Piano_off
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Yoga_off

In [6]:
# For every user add a random number of lessons taught for his/her expert skill

for index, row in concatenated_df.iterrows():
    expert_skill = row['Expert_skill']
    matching_column = str(expert_skill)
    random_number = max(0, int(np.random.normal(10, 4)))
    concatenated_df.at[index, matching_column] = random_number

concatenated_df

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,...,Count_Motion graphics_off,Count_Tap dance_off,Count_Ballroom dance_off,Count_Video editing_off,Count_Social Media_off,Count_Image processing_off,Count_Landscape photography_off,Count_Film making_off,Count_Poetry writing_off,Count_Play writing_off
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
concatenated_df_numeric = concatenated_df.apply(pd.to_numeric, errors='coerce')
numeric_columns = concatenated_df_numeric.select_dtypes(include=np.number)
concatenated_df['Sum_Skills_Off'] = numeric_columns.sum(axis=1)
concatenated_df

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,...,Count_Tap dance_off,Count_Ballroom dance_off,Count_Video editing_off,Count_Social Media_off,Count_Image processing_off,Count_Landscape photography_off,Count_Film making_off,Count_Poetry writing_off,Count_Play writing_off,Sum_Skills_Off
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0

In [8]:
# Create a new column that indicates how many lessons a user has taken, 
# while ensuring that the number of lessons given and taken are balanced


# Step 1: Calculate the sum of the "Sum_Skills_off" column
# Step 2: Generate random numbers for "Sum_Skills_rec" column
# Generate a random number between 80% and 120% of the corresponding value in "Sum_Skills_off" (to ensure a max deviation of 20%)
# Step 3: Adjust the values of the "Sum_Skills_rec" column to match the sum of "Sum_Skills_off"
# Randomly adjust values to match the sum of "Sum_Skills_off" (+ ensure the new value is not negative)


sum_skills_off_sum = concatenated_df['Sum_Skills_Off'].sum()

for index, row in concatenated_df.iterrows():
    min_value = int(0.8 * row['Sum_Skills_Off'])
    max_value = int(1.2 * row['Sum_Skills_Off'])
    if min_value < max_value:
        random_number = np.random.randint(min_value, max_value + 1)  
    else:
        random_number = min_value
    concatenated_df.at[index, 'Sum_Skills_Rec'] = random_number

sum_skills_rec_sum = concatenated_df['Sum_Skills_Rec'].sum()

difference = sum_skills_off_sum - sum_skills_rec_sum
if difference != 0:
    while difference != 0:
        index = np.random.randint(len(concatenated_df))
        current_value = concatenated_df.at[index, 'Sum_Skills_Rec']
        new_value = current_value + np.sign(difference)
        if new_value >= 0:  
            concatenated_df.at[index, 'Sum_Skills_Rec'] = new_value
            difference -= np.sign(difference)

concatenated_df

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,...,Count_Ballroom dance_off,Count_Video editing_off,Count_Social Media_off,Count_Image processing_off,Count_Landscape photography_off,Count_Film making_off,Count_Poetry writing_off,Count_Play writing_off,Sum_Skills_Off,Sum_Skills_Rec
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0
2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,12.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,10.0
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,12.0
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,8.0
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,14.0

In [9]:
# Sum of skills offered and received must be the same (there is always a teacher and a learner in a skill transaction)
print(concatenated_df['Sum_Skills_Off'].sum())
print(concatenated_df['Sum_Skills_Rec'].sum())

7421.0
7421.0

In [10]:
skill_domains = [
    "Agriculture",
    "Animal Care",
    "Art",
    "Beauty",
    "Dance",
    "Music",
    "Writing",
    "Language",
    "Health",
    "Sports",
    "Food",
    "Technology",
    "Photo",
    "Video"
]

skills_df = pd.DataFrame(columns=skill_domains)

skills_df.head()

Empty DataFrame
Columns: [Agriculture, Animal Care, Art, Beauty, Dance, Music, Writing, Language, Health, Sports, Food, Technology, Photo, Video]
Index: []

In [11]:
concatenated_df2 = pd.concat([concatenated_df, skills_df], axis=1)
concatenated_df2.head()

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,...,Dance,Music,Writing,Language,Health,Sports,Food,Technology,Photo,Video
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Skill domains and respective skills
skills_dict = {
    'Agriculture': ['Count_Farming_off', 'Count_Fishery_off', 'Count_Gardening_off'],
    'Animal Care': ['Count_Pet grooming_off', 'Count_Pet training_off'],
    'Art': ['Count_Drawing_off', 'Count_Painting_off', 'Count_Sculpture_off', 'Count_Print making_off', 'Count_Poetry_off'],
    'Beauty': ['Count_Make-up_off', 'Count_Facials_off', 'Count_Pedicure & Manicure_off', 'Count_Hair care_off'],
    'Dance': ['Count_Ballet_off', 'Count_Tap dance_off', 'Count_Jazz dance_off', 'Count_Salsa_off', 'Count_Ballroom dance_off'],
    'Music': ['Count_Piano_off', 'Count_Guitar_off', 'Count_Drumming_off', 'Count_Trumpet_off', 'Count_Composing_off'],
    'Writing': ['Count_Script writing_off', 'Count_Play writing_off', 'Count_Poetry writing_off', 'Count_Caligraphy_off', 'Count_Blogging_off', 'Count_Journalism_off'],
    'Language': ['Count_German_off', 'Count_Spanish_off', 'Count_Arabic_off', 'Count_French_off', 'Count_English_off'],
    'Health': ['Count_Nutrition_off', 'Count_Fitness & Excercise_off', 'Count_Wellness_off'],
    'Sports': ['Count_Tennis_off', 'Count_Football_off', 'Count_Basketball_off', 'Count_Yoga_off', 'Count_Baseball_off', 'Count_Gymnastic_off'],
    'Food': ['Count_Cooking_off', 'Count_Baking_off', 'Count_Grilling_off', 'Count_Meal planning_off', 'Count_Sautéing_off'],
    'Technology': ['Count_Programming_off', 'Count_Graphic design_off', 'Count_Data Analysis_off', 'Count_Photoshop_off', 'Count_Social Media_off'],
    'Photo': ['Count_Camera handling_off', 'Count_Photo editing_off', 'Count_Lighting_off', 'Count_Landscape photography_off', 'Count_Portrait photography_off', 'Count_Image processing_off'],
    'Video': ['Count_Video editing_off', 'Count_Film making_off', 'Count_Animation_off', 'Count_Motion graphics_off', 'Count_Visual effects_off']
}

In [13]:
# Based on the expert skill, find out in which skill domain or category the user has this expertise

# Create a new column called "domain"
# Iterate over each row in the DataFrame
# Iterate over each category in the skills_dict
# Check if the expert_skill matches any skill in the category
# Assign the category to the "domain" column
# Exit the loop once a match is found


concatenated_df2['Domain'] = None

for index, row in concatenated_df2.iterrows():
    expert_skill = row['Expert_skill']
    for category, skills in skills_dict.items():
        if any(expert_skill == skill for skill in skills):
            concatenated_df2.at[index, 'Domain'] = category
            break  

pd.set_option('display.max_columns', None)
concatenated_df2.head()

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,Count_Make_up_off,Count_Facials_off,Count_Pedicure_and_Manicure_off,Count_Hair_care_off,Count_Ballet_off,Count_Tap_dance_off,Count_Jazz_dance_off,Count_Salsa_off,Count_Ballroom_dance_off,Count_Piano_off,Count_Guitar_off,Count_Drumming_off,Count_Trumpet_off,Count_Composing_off,Count_Script_writing_off,Count_Play_writing_off,Count_Poetry_writing_off,Count_Caligraphy_off,Count_Blogging_off,Count_Journalism_off,Count_German_off,Count_Spanish_off,Count_Arabic_off,Count_French_off,Count_English_off,Count_Nutrition_off,Count_Fitness_and_Excercise_off,Count_Wellness_off,Count_Tennis_off,Count_Football_off,Count_Basketball_off,Count_Yoga_off,Count_Baseball_off,Count_Gymnastic_off,Count_Cooking_off,Count_Baking_off,Count_Grilling_off,Count_Meal_planning_off,Count_Sautéing_off,Count_Programming_off,Count_Graphic_design_off,Count_Data_Analysis_off,Count_Photoshop_off,Count_Social_Media_off,Count_Camera_handling_off,Count_Photo_editing_off,Count_Lighting_off,Count_Landscape_photography_off,Count_Portrait_photography_off,Count_Image_processing_off,Count_Video_editing_off,Count_Film_making_off,Count_Animation_off,Count_Motion_graphics_off,Count_Visual_effects_off,Expert_skill,Count_Graphic design_off,Count_Pedicure & Manicure_off,Count_Pet training_off,Count_Pet grooming_off,Count_Visual effects_off,Count_Hair care_off,Count_Script writing_off,Count_Make-up_off,Count_Data Analysis_off,Count_Fitness & Excercise_off,Count_Camera handling_off,Count_Photo editing_off,Count_Print making_off,Count_Meal planning_off,Count_Jazz dance_off,Count_Portrait photography_off,Count_Motion graphics_off,Count_Tap dance_off,Count_Ballroom dance_off,Count_Video editing_off,Count_Social Media_off,Count_Image processing_off,Count_Landscape photography_off,Count_Film making_off,Count_Poetry writing_off,Count_Play writing_off,Sum_Skills_Off,Sum_Skills_Rec,Agriculture,Animal Care,Art,Beauty,Dance,Music,Writing,Language,Health,Sports,Food,Technology,Photo,Video,Domain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Tennis_off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sports
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Graphic design_off,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology
2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Farming_off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Agriculture
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Football_off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sports
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Pedicure & Manicure_off,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beauty

In [14]:
# Enter in the column of the skill domain where the user has the expert skill
# how many lessons the user has given in this domain 

# Iterate over each row in the DataFrame
# Check if the domain column exists in the DataFrame
# Copy the value from the "Sum_Skills_off" column to the matched column

for index, row in concatenated_df2.iterrows():
    domain = row['Domain']
    sum_skills_off = row['Sum_Skills_Off']
    
    if domain in concatenated_df2.columns:
        concatenated_df2.at[index, domain] = int(sum_skills_off)

concatenated_df2.head()

,Count_Farming_off,Count_Fishery_off,Count_Gardening_off,Count_Pet_grooming_off,Count_Pet_training_off,Count_Drawing_off,Count_Painting_off,Count_Sculpture_off,Count_Print_making_off,Count_Poetry_off,Count_Make_up_off,Count_Facials_off,Count_Pedicure_and_Manicure_off,Count_Hair_care_off,Count_Ballet_off,Count_Tap_dance_off,Count_Jazz_dance_off,Count_Salsa_off,Count_Ballroom_dance_off,Count_Piano_off,Count_Guitar_off,Count_Drumming_off,Count_Trumpet_off,Count_Composing_off,Count_Script_writing_off,Count_Play_writing_off,Count_Poetry_writing_off,Count_Caligraphy_off,Count_Blogging_off,Count_Journalism_off,Count_German_off,Count_Spanish_off,Count_Arabic_off,Count_French_off,Count_English_off,Count_Nutrition_off,Count_Fitness_and_Excercise_off,Count_Wellness_off,Count_Tennis_off,Count_Football_off,Count_Basketball_off,Count_Yoga_off,Count_Baseball_off,Count_Gymnastic_off,Count_Cooking_off,Count_Baking_off,Count_Grilling_off,Count_Meal_planning_off,Count_Sautéing_off,Count_Programming_off,Count_Graphic_design_off,Count_Data_Analysis_off,Count_Photoshop_off,Count_Social_Media_off,Count_Camera_handling_off,Count_Photo_editing_off,Count_Lighting_off,Count_Landscape_photography_off,Count_Portrait_photography_off,Count_Image_processing_off,Count_Video_editing_off,Count_Film_making_off,Count_Animation_off,Count_Motion_graphics_off,Count_Visual_effects_off,Expert_skill,Count_Graphic design_off,Count_Pedicure & Manicure_off,Count_Pet training_off,Count_Pet grooming_off,Count_Visual effects_off,Count_Hair care_off,Count_Script writing_off,Count_Make-up_off,Count_Data Analysis_off,Count_Fitness & Excercise_off,Count_Camera handling_off,Count_Photo editing_off,Count_Print making_off,Count_Meal planning_off,Count_Jazz dance_off,Count_Portrait photography_off,Count_Motion graphics_off,Count_Tap dance_off,Count_Ballroom dance_off,Count_Video editing_off,Count_Social Media_off,Count_Image processing_off,Count_Landscape photography_off,Count_Film making_off,Count_Poetry writing_off,Count_Play writing_off,Sum_Skills_Off,Sum_Skills_Rec,Agriculture,Animal Care,Art,Beauty,Dance,Music,Writing,Language,Health,Sports,Food,Technology,Photo,Video,Domain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Tennis_off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,Sports
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Graphic design_off,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,Technology
2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Farming_off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,12.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Agriculture
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Football_off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,Sports
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Count_Pedicure & Manicure_off,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,8.0,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beauty

In [15]:
concatenated_df2.drop(columns=['Expert_skill','Domain'], inplace=True)
concatenated_df2.to_csv('Track_Record.csv', index=False)